app = 'annix-app'
primary_region = 'jnb'

[build]

[deploy]
  release_command = 'sh -c "cd annix-backend && npx ts-node --project tsconfig.json --transpile-only ./node_modules/typeorm/cli -d ./src/config/data-source.ts migration:run"'
  release_command_timeout = '40m'

[env]
  NODE_ENV = 'production'
  PORT = '4000'
  NEXT_PUBLIC_API_URL = '/api'
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = '__NEXT_PUBLIC_GOOGLE_MAPS_API_KEY__'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[checks]
  [checks.health]
    grace_period = '30s'
    interval = '30s'
    method = 'GET'
    path = '/health'
    port = 4000
    timeout = '10s'
    type = 'http'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
