app = 'annix-backend'
primary_region = 'jnb'

[build]

[deploy]
  release_command = 'npx ts-node --transpile-only ./node_modules/typeorm/cli -d ./src/config/data-source.ts migration:run'
  release_command_timeout = '10m'

[env]
  NODE_ENV = 'production'
  PORT = '4000'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health]
    grace_period = '30s'
    interval = '30s'
    method = 'GET'
    path = '/'
    port = 4000
    timeout = '10s'
    type = 'http'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
